### ISSUE TITLE
Is there a plan to add support for Mysql 8?

### ISSUE THREAD

**Issue by emmanuelcohen** [realrolfje/anonimatron#101]
Hi,
I recently moved to mysql v8 and anonimatron won't work with mysql beyond version 5.
It would be nice to have a new version with embedded support to v8.
Otherwise, can you describe a workaround that would help me user mysql 8 with the current version?

**Additional context:**

This is the original error I got:

```
ecohen@LAPTOP:~/dev/anonimatron$ ./anonimatron.sh -config config/config_portal.xml
Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
        at com.mysql.jdbc.Util.getInstance(Util.java:384)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3566)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3498)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919)
        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4004)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1284)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2312)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2122)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:774)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:49)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:375)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:289)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.setConnection(JdbcAnonymizerService.java:111)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.<init>(JdbcAnonymizerService.java:49)
        at com.rolfje.anonimatron.Anonimatron.anonymize(Anonimatron.java:71)
        at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:49)

```

**Comment by realrolfje** [comment]
I ran into this very same problem very recently, so yes, the jdbc driver will be upgraded to support MySQL8 in the next release.

**Comment by emmanuelcohen** [comment]
Great!
Thank you

**Comment by realrolfje** [comment]
Solved in develop branch, will be part of release 1.14
