### ISSUE TITLE
This driver can be used only with SQL Server 2005 or later

### ISSUE THREAD

**Issue by PedroAvelar** [realrolfje/anonimatron#114]
Hi my friends!

I am trying to run Anonimatron on my SQL SERVER table to perform a test and I am getting the error described in the title.

The problem is that my SQL Server DB is on 2008 version and a have updated the drivers on "/root/anonimatron/anonimatron-1.14/jdbcdrivers" with the most recently jdbc "mssql-jdbc-8.4.1.jre8.jar"

`root@mysql-pedro-tmp:~/anonimatron/anonimatron-1.14# ./anonimatron.sh -config sqlserver_clientes.xml -synonyms synonyms_sqlserver.xml
Oct 23, 2020 8:52:08 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: af6c470b-773c-4452-bb80-2c74a96ca005 Prelogin error: host 10.215.129.86 port 11433 Unexpected end of prelogin response after 0 bytes read

Oct 23, 2020 8:52:29 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:2 ClientConnectionId: c17bf39f-8d32-4eb8-b3a5-b633c65176ea Prelogin error: host 10.215.129.86 port 11433 Unexpected end of prelogin response after 0 bytes read
Oct 23, 2020 8:52:49 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:3 ClientConnectionId: d0296e52-fb8e-4722-9384-7f6958a2f020 Prelogin error: host 10.215.129.86 port 11433 Unexpected end of prelogin response after 0 bytes read
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host 10.215.129.86, port 11433 has failed. Error: "The driver received an unexpected pre-login response. Verify the connection properties and check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. This driver can be used only with SQL Server 2005 or later.". ClientConnectionId:af6c470b-773c-4452-bb80-2c74a96ca005
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3151)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3140)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.Prelogin(SQLServerConnection.java:2882)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2704)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2362)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2213)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1276)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:861)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.setConnection(JdbcAnonymizerService.java:95)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.<init>(JdbcAnonymizerService.java:37)
        at com.rolfje.anonimatron.Anonimatron.anonymize(Anonimatron.java:93)
        at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:48)`

**Comment by realrolfje** [comment]
Hello, it could be that TCP is disabled on your MSSQL server. For MSSQL 2008 this is the default. Can you please have a look at this StackOverflow answer: https://stackoverflow.com/questions/11335797/problems-logging-into-mssql-server-from-java and see if that solves your problem?

**Comment by PedroAvelar** [comment]
Hi @realrolfje,

I managed to solve this problem.

The error message "This driver can be used only with SQL Server 2005 or later" is generic and does not report the nature of the problem.

My problem was in the network release between my machine running Anonimatron and my SQL Server database.

The driver was correct all the time.

Thanks for your attention and all the help.
