### ISSUE TITLE
Anonymizing interbase database fails with error about concurrency type

### ISSUE THREAD

**Issue by roaldvandoorn** [realrolfje/anonimatron#166]
Anonimatron version: 1.15
Operating system and version: Windows 10
Java runtime (`java -version`): 8 Update 331

#### Executed commands or actions:
Tried to Anonymize an interbase database using the InterClient library

#### Expected outcome or behavior:
Anonymized tables

#### Actual outcome or behavior:
Error message during anonymization:

```
2022-05-02 15:22:23,444 INFO  (Configuration.java:0) Configuration read from C:\Users\roald.van.doorn\Desktop\anonimatron-1.15\config.xml []
2022-05-02 15:22:23,587 INFO  (JdbcAnonymizerService.java:0) Conected to 'jdbc:interbase://localhost:3051/d:/sam/data/sam_anon.ib' with user 'sysdba'. []
2022-05-02 15:22:23,945 INFO  (JdbcAnonymizerService.java:0) Table RELATIE has 255933 rows to process. []
2022-05-02 15:22:23,973 INFO  (JdbcAnonymizerService.java:0) Table ADRES has 48362 rows to process. []
2022-05-02 15:22:24,003 FATAL (JdbcAnonymizerService.java:0) Anonymyzation stopped because of fatal error. [Table 'RELATIE']
interbase.interclient.DriverNotCapableException: [interclient] Unsupported feature: Invalid or Unsupported Concurrency type or Scrollablity, only CONCUR_READ_ONLY and TYPE_FORWARD_ONLY supported.
See API reference for exception interbase.interclient.DriverNotCapableException
	at interbase.interclient.Connection.createStatement(Unknown Source)
	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.processTableColumns(JdbcAnonymizerService.java:149)
	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.anonymizeTableInPlace(JdbcAnonymizerService.java:128)
	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.anonymize(JdbcAnonymizerService.java:81)
	at com.rolfje.anonimatron.Anonimatron.anonymize(Anonimatron.java:94)
	at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:48)
```

**Comment by roaldvandoorn** [comment]
Forgot to add, Interbase XE3 Update 4.
