### ISSUE TITLE
Mariadb connection

### ISSUE THREAD

**Issue by anatoly-trepet** [realrolfje/anonimatron#191]
**I have issue when try to use "anonimatron" tool:**
**CONFIG.XML:**
<?xml version="1.0" encoding="UTF-8"?>
<configuration salt="examplesalt"
    jdbcurl="jdbc:mariadb://127.0.0.1/db" userid="user" password="pwd">
    <anonymizerclass>org.sf.anonimatron.CommunityAnonymizer</anonymizerclass>
    <table name="tsis_test">
        <column name="name" type="ROMAN_NAME" size="-1"/>
        <column name="value" type="EMAIL_ADDRESS" size="-1"/>
    </table>
</configuration>

**I put "mariadb-java-client-2.2.5.jar" to jdbcdrivers library

and executed command:
.\anonimatron.bat -config .\config.xml -dryrun -synonyms synonyms.xml

And erorr apear:**

Exception in thread "main" org.exolab.castor.xml.MarshalException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.{File: [not available]; line: 1; column: 1}
        at org.exolab.castor.xml.Unmarshaller.convertSAXExceptionToMarshalException(Unmarshaller.java:832)
        at org.exolab.castor.xml.Unmarshaller.unmarshal(Unmarshaller.java:703)
        at org.exolab.castor.xml.Unmarshaller.unmarshal(Unmarshaller.java:589)
        at com.rolfje.anonimatron.configuration.Configuration.readFromFile(Configuration.java:53)
        at com.rolfje.anonimatron.Anonimatron.getConfiguration(Anonimatron.java:64)
        at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:47)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1466)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:993)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at org.exolab.castor.xml.Unmarshaller.unmarshal(Unmarshaller.java:694)
        ... 4 more

**Comment by realrolfje** [comment]
This is not a problem with MariaDB but with the config file. The config file must be plain text (not created in MSWord or TextEdit) and The first bytes should be exactly 3C 3F 78 6D 6C, which is <?xml.
