### ISSUE TITLE
Getting error: "Do not know how to anonymize type 'DATE'"

### ISSUE THREAD

**Issue by ShubhankitRoy** [realrolfje/anonimatron#5]
Hi there

I have a MySQL table that has a field of type 'DATETIME'. When I try to anonymize this table I get an UnsupportedOperationException saying "Do not know how to anonymize type 'DATE' "
Following is an excerpt from my config file: 
`<table name="contact_">
	<column name="birthday" type="DATE" />
</table>`

Can you kindly let me know what is going wrong here? Same exception is thrown if the field is of type 'DATE'.

Best
Shubhankit

**Comment by macropin** [comment]
I've reproduced this ```anonimatron_1  | Anonymizing table 'domain_operations', total progress  [0%, ETA 7:34:32 PM]Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Can not anonymize objects of type class java.sql.Timestamp
anonimatron_1  | 	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.processTableColumns(JdbcAnonymizerService.java:241)
anonimatron_1  | 	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.anonymizeTableInPlace(JdbcAnonymizerService.java:154)
anonimatron_1  | 	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.anonymize(JdbcAnonymizerService.java:94)
anonimatron_1  | 	at com.rolfje.anonimatron.Anonimatron.anonymize(Anonimatron.java:99)
anonimatron_1  | 	at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:67)
anonimatron_1  | Caused by: java.lang.UnsupportedOperationException: Can not anonymize objects of type class java.sql.Timestamp
anonimatron_1  | 	at com.rolfje.anonimatron.anonymizer.DateAnonymizer.anonymize(DateAnonymizer.java:42)
anonimatron_1  | 	at com.rolfje.anonimatron.anonymizer.AnonymizerService.anonymize(AnonymizerService.java:92)
anonimatron_1  | 	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService$2.processColumn(JdbcAnonymizerService.java:140)
anonimatron_1  | 	at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.processTableColumns(JdbcAnonymizerService.java:212)
anonimatron_1  | 	... 4 more
anonimatron_1  | /usr/src/app```

column is mysql type `timestamp`.

**Comment by realrolfje** [comment]
Currently the DateAnonymizer only handles java.sql.Date objects. Apparently the resultset returns DateTime objects because the database contains the timestamp datatype. I need to add a testcase for this situation and either fix the date anonymizer or create a datetime anonymizer

**Comment by realrolfje** [comment]
Related to #2

**Comment by realrolfje** [comment]
I am cleaning up old issues and have put more investigation into this possible problem.

According to current MySQL Connector/J docs, ResultSetMetaData.getColumnClassName() maps:

- MySQL DATE -> java.sql.Date
- MySQL TIMESTAMP -> java.sql.Timestamp
- MySQL TIME -> java.sql.Time
- MySQL DATETIME -> currently java.time.LocalDateTime

Source: MySQL Connector/J “Java, JDBC, and MySQL Types” table:  https://dev.mysql.com/doc/connector-j/en/connector-j-reference-type-conversions.html

So if the database column is truly DATE, ResultSet.getObject() should not normally return a Timestamp.

So:

- A MySQL DATETIME column is not a DATE column, even if the application uses it to store date-only values.
- Older Connector/J versions commonly exposed DATETIME as timestamp-like values.
- Current Connector/J even has a treatMysqlDatetimeAsTimestamp option, which explicitly changes DATETIME handling toward java.sql.Timestamp:    https://dev.mysql.com/doc/connectors/en/connector-j-connp-props-datetime-types-processing.html

This means that this issue is more likely a configuration problem, or a feature request for changing dates in timestamps.
