### ISSUE TITLE
build custom Anonymizer

### ISSUE THREAD

**Issue by J-SM** [realrolfje/anonimatron#64]
I've tried to build the attached Anonymizer for UK postcodes

javac.exe  -classpath D:\anonimatron\libraries\* -d D:\anonimatron\anonymizers\UkPostCodeAnonymizer.java
jar -cvf D:\anonimatron\anonymizers\UkPostCodeAnonymizer.jar D:\anonimatron\anonymizers\UkPostCodeAnonymizer.class  

and the resultant jar file is in the anonymizers folder however when i include in the config

`<anonymizerclass>com.animed.UkPostCodeAnonymizer</anonymizerclass>`

and use type="UK_POST_CODE" on a column for my customer_address_entity table i get the following output from the anonimatron.bat using the -dryrun option.

`Pre-scanning table 'customer_address_entity', total progress  [0%, ETA 12:10:08]Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Do not know how to anonymize type 'UK_POST_CODE'.
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.processTableColumns(JdbcAnonymizerService.java:241)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.preScanTable(JdbcAnonymizerService.java:132)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.anonymize(JdbcAnonymizerService.java:86)
        at com.rolfje.anonimatron.Anonimatron.anonymize(Anonimatron.java:90)
        at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:44)
Caused by: java.lang.UnsupportedOperationException: Do not know how to anonymize type 'UK_POST_CODE'.
        at com.rolfje.anonimatron.anonymizer.AnonymizerService.getAnonymizer(AnonymizerService.java:151)
        at com.rolfje.anonimatron.anonymizer.AnonymizerService.prepare(AnonymizerService.java:159)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService$1.processColumn(JdbcAnonymizerService.java:127)
        at com.rolfje.anonimatron.jdbc.JdbcAnonymizerService.processTableColumns(JdbcAnonymizerService.java:212)
        ... 4 more`

I have attached my source .java and the resultant .jar. what do i need to do to get this new anonymizer working?

[anonymizers.zip](https://github.com/realrolfje/anonimatron/files/3712356/anonymizers.zip)

**Comment by realrolfje** [comment]
Thank you for building an anonymizer for anonimaron. I have unpacked your zipfile and got it to (almost) work:

First, the jar file is not correct. To create a correct jar file, your class must be in the same directory as the package name. To do that, move the compiled class file to `com/animed/UkPostCodeAnonymizer.class` and then create a jar file as follows (all output shown):

```sh
$ jar -cvf UkPostCodeAnonymizer.jar com
added manifest
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/animed/(in = 0) (out= 0)(stored 0%)
adding: com/animed/UkPostCodeAnonymizer.class(in = 1271) (out= 687)(deflated 45%)
```

To test that this works, I placed the jar file in the anonymizers directory, and created a simple config file and csv input file. I used this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration salt="examplesalt">
    <anonymizerclass>com.animed.UkPostCodeAnonymizer</anonymizerclass>
    <file inFile="mydatafile.in.csv"
        reader="com.rolfje.anonimatron.file.CsvFileReader"
        outFile="mydatafile.out.csv"
         writer="com.rolfje.anonimatron.file.CsvFileWriter">
        <column name="1" type="UK_POST_CODE" size="-1"/>
    </file>
</configuration>
```

The class is loaded and your anonymizer tries to parse the first field passed in, but fails with the following error:

```sh
./anonimatron.sh -config ukexampleconfig.xml
Files to process: 1
Anonymizing from anonimatron-1.11.1/mydatafile.in.csv
              to anonimatron-1.11.1/mydatafile.out.csv
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.animed.UkPostCodeAnonymizer.buildZipCode(UkPostCodeAnonymizer.java:31)
	at com.animed.UkPostCodeAnonymizer.anonymize(UkPostCodeAnonymizer.java:20)
	at com.rolfje.anonimatron.anonymizer.Anonymizer.anonymize(Anonymizer.java:57)
	at com.rolfje.anonimatron.anonymizer.AnonymizerService.anonymize(AnonymizerService.java:92)
	at com.rolfje.anonimatron.file.FileAnonymizerService.anonymize(FileAnonymizerService.java:200)
	at com.rolfje.anonimatron.file.FileAnonymizerService.anonymize(FileAnonymizerService.java:186)
	at com.rolfje.anonimatron.file.FileAnonymizerService.anonymize(FileAnonymizerService.java:87)
	at com.rolfje.anonimatron.Anonimatron.anonymize(Anonimatron.java:94)
	at com.rolfje.anonimatron.Anonimatron.main(Anonimatron.java:44)
```

Something fails at line 31 in UkPostCodeAnonymizer.java. I see that your Java code is not really Java:

```java
		String $str=new String();
		$str += (char)(64+(random.nextInt(0-26) + 26)); 
```

In these lines, the text `random.nextInt(0-26)` does not mean "a random number between 0 and 26", but rather "a positive random number not higher than -26", which is semantically wrong. I also notice that you are using $ signs in your variable name, which is something you'd do in shell scripts but not in Java.

I'd recommend you take an [https://www.codecademy.com/learn/learn-java/](online introductory course) in Java. Writing an Anonymizer would be a nice way to test your skills.

I'd be happy to help you write it, or if you really need a postal code anonymizer fast I can probably cook something up for you this weekend.

It would also be a nice addition to Anonimatron.
